version: '3'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql2:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306

volumes:
  mysql2: