version: '3'

services:
  demo:
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/demo:cached
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: ru
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: